#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup /etc/systemd/system/wireguard_ui.service
ynh_backup /etc/systemd/system/wireguard@.path
ynh_backup /etc/systemd/system/wireguard@.service

#=================================================
# BACKUP VARIOUS FILES
#=================================================

# Backup the wireguard interface config
ynh_backup "/etc/wireguard"

# Backing up specific config file, in case of it is not in /etc/wireguard
ynh_backup "$(jq -r 'select(.config_file_path | startswith("/etc/wireguard/") | not) | .config_file_path' $install_dir/db/server/global_settings.json)" || true

# Backup the sysctl config file to enable port forwarding
ynh_backup "/etc/sysctl.d/$app.conf"

# Backup the nftables config file to configure firewall
ynh_backup --src_path="/etc/nftables.d/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
