#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

interface=$(ip route | awk '/default/ { print $5 }' | head -n1)
main_domain=$(cat /etc/yunohost/current_host)

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=interface --value=$interface

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

#=================================================
# CONFIGURING WIREGUARD
#=================================================

# Create db directory for securing it later
mkdir -p $install_dir/db/server

# Add interface configuration file for the Web UI
ynh_config_add --template="interfaces.json" --destination="$install_dir/db/server/interfaces.json"
ynh_delete_file_checksum "$install_dir/db/server/interfaces.json"

# Add configuration for the Web UI
ynh_config_add --template="wireguard-ui.env" --destination="$install_dir/wireguard-ui.env"

# Create WireGuard configuration directory
mkdir -p /etc/wireguard

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

# Create a dedicated systemd config for the web UI
ynh_config_add_systemd --service=wireguard_ui --template=wireguard_ui.service

# Create dedicated systemd configs for starting and monitoring WireGuard's configuration
cp ../conf/wireguard@.service /etc/systemd/system/wireguard@.service
cp ../conf/wireguard@.path /etc/systemd/system/wireguard@.path
systemctl daemon-reload
systemctl enable --quiet wireguard@wg0.service
systemctl enable --quiet --now wireguard@wg0.path

#=================================================
# ENABLE PORT FORWARDING
#=================================================
ynh_script_progression "Enabling port forwarding..."

ynh_config_add --template="sysctl.conf" --destination="/etc/sysctl.d/$app.conf"
sysctl -p /etc/sysctl.d/$app.conf

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"
chmod 750 /etc/wireguard
chmod -R o-rwx /etc/wireguard
chown -R $app: /etc/wireguard

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add wg-quick@wg0 --description="WireGuard VPN" --needs_exposed_ports="$port_wg" --test_status="wg show | grep wg0"
yunohost service add wireguard_ui --description="WireGuard UI"

#=================================================
# START UI SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting the systemd service for the UI..."

ynh_systemctl --service=wireguard_ui --action="start" --wait_until="http server started" --log_path="systemd" --timeout=30

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed. You may need to reboot your server before being able to start the WireGuard service."
