#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the services from the list of services known by Yunohost (added from `yunohost service add`)

if ynh_hide_warnings yunohost service status wireguard_ui >/dev/null
then
	ynh_script_progression "Removing WireGuard UI service integration..."
	yunohost service remove wireguard_ui
fi

if ynh_hide_warnings yunohost service status wg-quick@wg0 >/dev/null
then
	ynh_script_progression "Removing WireGuard service integration..."
	yunohost service remove wg-quick@wg0
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Stop wg-quick service
systemctl stop wg-quick@wg0

# YunoHost does not handle services not ending with .service, let's remove it manually
systemctl stop wireguard@wg0.path
systemctl disable wireguard@wg0.path --quiet
ynh_safe_rm "/etc/systemd/system/wireguard@.path"

systemctl stop wireguard@wg0.service
systemctl disable wireguard@wg0.service --quiet
ynh_safe_rm "/etc/systemd/system/wireguard@.service"

ynh_config_remove_systemdwireguard_ui

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression "Removing app main directory..."

# Remove WireGuard configuration directory securely
ynh_safe_rm "/etc/wireguard"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated nginx config
ynh_config_remove_nginx

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Removing logrotate configuration..."

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================

# Remove sudoers file
ynh_safe_rm "/etc/sudoers.d/${app}_ynh"

# Remove sysctl file for port forwarding
ynh_safe_rm "/etc/sysctl.d/$app.conf"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
