#!/bin/bash

source _common.sh

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if ynh_hide_warnings yunohost service status wireguard_ui >/dev/null; then
	yunohost service remove wireguard_ui
fi

if ynh_hide_warnings yunohost service status wg-quick@wg0 >/dev/null; then
	yunohost service remove wg-quick@wg0
fi

# Stop wg-quick service
systemctl stop wg-quick@wg0

# YunoHost does not handle services not ending with .service, let's remove it manually
systemctl stop wireguard@wg0.path
systemctl disable wireguard@wg0.path --quiet
ynh_safe_rm "/etc/systemd/system/wireguard@.path"

systemctl stop wireguard@wg0.service
systemctl disable wireguard@wg0.service --quiet
ynh_safe_rm "/etc/systemd/system/wireguard@.service"

ynh_config_remove_systemd wireguard_ui

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression "Removing app main directory..."

# Remove WireGuard configuration directory securely
ynh_safe_rm "/etc/wireguard"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

ynh_config_remove_nginx

ynh_config_remove_logrotate

#=================================================
# REMOVE VARIOUS FILES
#=================================================

# Remove sudoers file
ynh_safe_rm "/etc/sudoers.d/${app}_ynh"

# Remove sysctl file for port forwarding
ynh_safe_rm "/etc/sysctl.d/$app.conf"

# Remove app-specific firewall config
_ynh_config_remove_nftables

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
