#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"
ynh_restore "/etc/wireguard"

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
chmod 750 "$install_dir"
chmod -R o-rwx "$install_dir"
chown -R $app: "$install_dir"
chmod 750 /etc/wireguard
chmod -R o-rwx /etc/wireguard
chown -R $app: /etc/wireguard

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring $app's systemd service..."

ynh_restore /etc/systemd/system/wireguard_ui.service
ynh_restore /etc/systemd/system/wireguard@.service
ynh_restore /etc/systemd/system/wireguard@.path

systemctl daemon-reload

systemctl enable --quiet wireguard_ui.service
systemctl enable --quiet wireguard@wg0.service
systemctl enable --quiet --now wireguard@wg0.path

#=================================================
# ENABLE PORT FORWARDING
#=================================================
ynh_script_progression "Enabling port forwarding..."

ynh_restore "/etc/sysctl.d/$app.conf"
sysctl -p /etc/sysctl.d/$app.conf

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add wg-quick@wg0 --description="WireGuard VPN" --needs_exposed_ports="$port_wg" --test_status="wg show | grep wg0"
yunohost service add wireguard_ui --description="WireGuard UI"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore $(jq -r ".config_file_path" $install_dir/db/server/global_settings.json) || true

#=================================================
# START UI SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting the systemd service for the UI..."

ynh_systemctl --service=wireguard_ui --action="start" --wait_until="http server started" --log_path="systemd" --timeout=30

#=================================================
# RELOAD NGINX AND PHP-FPM
#=================================================
ynh_script_progression "Reloading NGINX web server..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app. You may need to reboot your server before being able to start the WireGuard service."
